## The step loop. One tick is one turn; the eight numbered steps of the
## design note run in this order and nothing else mutates the world.
##
## `import generals/sim` sees everything: this module re-exports the sim
## modules the way the starter's `src/ctf/sim.nim` does, so the native server
## and the wasm replay entry compile against one surface.

import std/[json, strutils]
import sim_types, sim_config, board, vision, events, sim_state, resolve,
  scoring, captain, baselines, directives

export sim_types, sim_config, board, vision, events, sim_state, resolve,
  scoring, captain, baselines, directives

proc viewOf*(sim: Sim, seat: int): SeatView =
  var alive: array[Seats, bool]
  var land, armyTotal, cities, outTurn, outTo: array[Seats, int]
  for other in 0 ..< Seats:
    alive[other] = sim.stats[other].alive
    land[other] = sim.stats[other].land
    armyTotal[other] = int(sim.stats[other].army)
    cities[other] = sim.stats[other].cities
    outTurn[other] = sim.stats[other].eliminatedTurn
    outTo[other] = sim.stats[other].eliminatedBy
  buildView(sim.board, sim.memory[seat], sim.visible[seat], seat, sim.turn,
    sim.config.maxTurns, sim.config.growthPeriod, alive, land, armyTotal,
    cities, outTurn, outTo)

proc isDirectiveTurn*(sim: Sim): bool {.inline.} =
  sim.turn mod sim.config.directiveEvery == 0

proc directiveIndex*(sim: Sim): int {.inline.} =
  sim.turn div sim.config.directiveEvery

proc directiveCount*(sim: Sim): int {.inline.} =
  (sim.config.maxTurns + sim.config.directiveEvery - 1) div
    sim.config.directiveEvery

proc installPlan*(sim: var Sim, seat: int, plan: Plan, source: PlanSource,
    latencyMs: int) =
  ## Step 1: the structured plan is load-bearing INPUT, re-applied at
  ## playback before this same turn is stepped.
  sim.plan[seat] = clampPlan(plan, sim.board.w, sim.board.h)
  sim.planSource[seat] = source
  sim.planLatency[seat] = latencyMs
  sim.planTurn[seat] = sim.turn
  sim.havePlan[seat] = true
  sim.mission[seat].active = false
  if source == psLlm:
    sim.stats[seat].llmTurns.inc
  elif source == psFallback:
    sim.stats[seat].fallbackTurns.inc

proc howItWent*(sim: Sim, seat: int, sinceLand, sinceArmy, sinceCities: int): string =
  ## Generated by the engine, never by a model, and capped at 240 runes.
  let stat = sim.stats[seat]
  var parts: seq[string] = @[]
  let landDelta = stat.land - sinceLand
  if landDelta > 0:
    parts.add("claimed " & $landDelta & " tiles")
  elif landDelta < 0:
    parts.add("lost " & $(-landDelta) & " tiles")
  else:
    parts.add("held the same land")
  let cityDelta = stat.cities - sinceCities
  if cityDelta > 0:
    parts.add("took " & $cityDelta & " city")
  else:
    parts.add("broke no city")
  let armyDelta = int(stat.army) - sinceArmy
  parts.add("army " & (if armyDelta >= 0: "+" else: "") & $armyDelta)
  let crown = sim.board.generalCell[seat]
  if crown >= 0:
    parts.add("your crown holds " & $sim.board.armyOf(crown))
  truncateRunes(parts.join(", "), MaxHowItWentRunes)

proc compileMoves*(sim: var Sim): (array[Seats, Move], array[Seats, bool]) =
  ## Step 2. A pure function of (that seat's fogged view, its plan, its seat
  ## index) — the captain never reads a cell the seat cannot see.
  var moves: array[Seats, Move]
  var hasMove: array[Seats, bool]
  for seat in 0 ..< Seats:
    if not sim.stats[seat].alive:
      continue
    let view = sim.viewOf(seat)
    var mission = sim.mission[seat]
    let (move, emitted) = compileMove(view, sim.plan[seat], seat, mission,
      sim.config)
    sim.mission[seat] = mission
    if emitted:
      moves[seat] = move
      hasMove[seat] = true
    else:
      sim.stats[seat].passes.inc
  (moves, hasMove)

proc checkEndConditions*(sim: var Sim) =
  if sim.done:
    return
  if sim.aliveCount() == 1:
    sim.finish("complete", "conquest")
    return
  if sim.aliveCount() == 0:
    sim.finish("complete", "conquest")
    return
  if sim.turn >= sim.config.maxTurns:
    sim.finish("complete", "full_time")

proc stepTurn*(sim: var Sim) =
  ## Steps 2 to 8 of one turn. Step 1 (directive install) is the caller's:
  ## the decision layer collects the plans BEFORE this tick is stepped.
  if sim.done:
    return
  sim.frameEvents = newJArray()
  let (moves, hasMove) = sim.compileMoves()
  sim.resolveMoves(moves, hasMove)
  sim.growPerTurn()
  sim.turn.inc
  sim.growPeriodic()
  sim.updateVisionAndMemory()
  sim.checkGeneralsInvariants()
  sim.checkEndConditions()

proc turnsPlayed*(sim: Sim): int =
  sim.turn

proc endSummary*(sim: var Sim) =
  let scores = sim.rankSeats(sim.turnsPlayed())
  var landRow = newJArray()
  var rankRow = newJArray()
  for seat in 0 ..< Seats:
    landRow.add(%sim.stats[seat].land)
    rankRow.add(%scores[seat].rank)
  let winner = winnerSeat(scores)
  sim.record(seEnd, %*{
    "reason": sim.reason, "endRule": sim.endRule,
    "land": landRow, "rank": rankRow,
    "winner": (if winner >= 0: %winner else: newJNull())})
